---
- name: Install required rpms and dependencies
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Download rpm
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
        state: present

   
